spring:
  application:
    name: protopie
  r2dbc:
    url: ${POSTGRE_URL:r2dbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRE_USERNAME:postgres}
    password: ${POSTGRE_PASSWORD:password}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


app:
  jwt:
    secret: mySecretKey123456789012345678901234567890
    expiration: 86400000 # 24 Hours
  postgre:
    aes-key: ProtopieAESKeyForPostgreSQL12345